name: Build Package
inputs:
  tag:
    description: Tag for packages
  packages:
    description: Space separated package names

runs:
  using: composite
  steps:
  - name: build packages
    shell: python
    run: |
        import sys, os
        #sys.path.insert(0, '${{ github.action_path }}')
        print(os.getcwd())
        settings={
          "inputs" : {
              "tag": "${{ inputs.tag }}",
              "packages": "${{ inputs.packages }}".split()
          }
        }
        #from minpkg.CI import GithubHelper
        #helper=GithubHelper(settings=settings)
        #helper.run()
