name: Build Package
inputs:
  tag:
    description: Tag for packages
  packages:
    description: Space separated package names

runs:
  using: composite
  steps:
  - name: build packages
    shell: python
    run: |
        import sys, os
        os.environ["PYTHONPATH"]='${{ github.action_path }}'
        sys.path.insert(0, '${{ github.action_path }}')
        import json
        settings=json.loads("""{
            "inputs": ${{ toJSON(inputs) }},
            "env": ${{ toJSON(env) }},
            "github": ${{ toJSON(github) }} }""")
        settings["inputs"]["packages"]=settings["inputs"]["packages"].split()
        from minpkg.CI import GithubHelper
        helper=GithubHelper(settings=settings)
        helper.run()
