name: Build Package
inputs:
  name:
    description: Package name
    required: true
  version:
    description: Version
    required: true
  sources:
    description: Sources
    required: true

runs:
  using: composite
  steps:
  - id: Print-env
    shell: python
    run: |
        import os
        env = os.environ
        for key, value in os.environ.items():
          print(f"{key}={value}")
        
  - id: Test
    shell: python
    run: |
        import os
        inputs="""
           ${{ toJSON(inputs) }}
        """
        SRCS=os.environ.get("INPUT_SOURCE").splitlines()
        print(SRCS)
