name: Build Package
inputs:
  tag:
    description: Tag for packages
  packages:
    description: Space separated package names

runs:
  using: composite
  steps:
  - name: build packages
    shell: python
    run: |
        import sys, os
        mod_path=os.environ.get("GITHUB_ACTION_PATH")
        sys.path.insert(0, mod_path)
        settings={
          "inputs" : {
              "tag": "${{ inputs.tag }}",
              "packages": "${{ inputs.packages }}".split()
          }
        }
        from minpkg.CI import GithubHelper
        helper=GithubHelper(settings=settings)
        helper.run()
  
  - name: Test variables
    shell: python
    run: |
        import sys, os
        print(os.environ)
