name: Build vcpkg deps

on:
  workflow_dispatch:
    inputs:
      build_packages:
        description: 'Build Packages'
        required: false
        type: string
      exec_cmd:
        description: 'Execute command'
        required: false
        type: string
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  run-windows:
    runs-on: windows-latest
    permissions:
      packages: write
    defaults:
      run:
        shell: cmd
        
    steps:
    - name: Print variables
      env:
        GHCR_URL: https://nuget.pkg.github.com/donarturo11/index.json
        VCPKG_BINARY_SOURCES: clear; nuget,${{ env.GHCR_URL }},readwrite
      run: |
           set
    - name: Check options
      run: ${{ inputs.exec_cmd }}
           
    



