name: Build vcpkg deps

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Build Packages'
        required: false
        type: string
      triplet:
        description: 'Triplet'
        required: true
        default: 'x64-windows'
        type: string
      debug:
        description: 'Build debug'
        required: false
        default: false
        type: boolean

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  run-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
        PKG_MGMNT_TOKEN: ${{ secrets.PKG_MGMNT_TOKEN }}
        GHCR_URL: https://nuget.pkg.github.com/donarturo11/index.json
    steps:
    - name: Setup
      run: |
           nuget sources add ^
           -Name ghcr ^
           -Source %GHCR_URL% ^
           -Username donarturo11 ^
           -Password %PKG_MGMNT_TOKEN% ^
           -StorePasswordInClearText
    - name: Install packages
      run: |
          set "VCPKG_BINARY_SOURCES=clear;nuget,%GHCR_URL%,readwrite"
          vcpkg install ${{ inputs.packages }} ^
          --triplet ${{ inputs.triplet }} ${{ inputs.debug && '--debug' || '' }}
          



