name: Build common deps

on:
  workflow_dispatch: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
       include:
        - name: "windows-msvc"
          os: windows-latest
          toolchain:
            cc: 'cl.exe'
            cxx: 'cl.exe'
          sdks-prefix: 'C:/SDKs/windows-msvc'
        - name: "windows-gcc"
          os: windows-latest
          toolchain:
            cc: 'gcc.exe'
            cxx: 'gcc.exe'
          sdks-prefix: 'C:/SDKs/windows-mingw'
        - name: "linux-gcc"
          os: ubuntu-latest
          toolchain:
            cc: 'gcc'
            cxx: 'gcc'
          sdks-prefix: '/opt/SDKs/linux-gcc'
        - name: "macos-clang"
          os: macos-latest
          toolchain:
            cc: 'clang'
            cxx: 'clang++'
          sdks-prefix: '/opt/SDKs/macos-clang'
    
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Set up Visual Studio shell
      if: ${{ runner.os == "Windows" }}
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Setup MINGW
      if: ${{ runner.os == "Windows" }}
      shell: bash
      run:
        echo "C:\\mingw64\\bin" >> $GITHUB_PATH

    - name: Setup environment (General)
      env:
        CMAKE_GENERATOR: Ninja
        CMAKE_C_COMPILER: ${{ matrix.toolchain.cc }}
        CMAKE_CXX_COMPILER: ${{ matrix.toolchain.cxx }}
        SDKS_PREFIX: ${{ matrix.sdks-prefix }}
    
    - name: Setup environment for MacOS
      if: ${{ runner.os == 'macOS' }}
      env:
        CMAKE_OSX_ARCHITECTURES: 'x86_64 arm64'
        CMAKE_OSX_DEPLOYMENT_TARGET: 10.15
    
    - name: Test environment
      run: echo $(env)
#    - name: Build fftw
#      run: |
#          mkdir fftw3
#          curl -L https://www.fftw.org/fftw-3.3.10.tar.gz | tar -vxz --strip-components=1 -C fftw3
#          cmake -S fftw3 -B fftw3-build -DCMAKE_INSTALL_PREFIX=${{ matrix.deps-prefix }}/fftw3
#          cmake --build fftw3-build
#          cmake --install fftw3
          
          
          
      
          



