name: Build VCPKG repo

on:
  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
       include:
        - name: "windows-msvc"
          vcpkg-triplet: "x64-windows"
          os: windows-latest

    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get runner variables
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg-triplet }}
        OWNCLOUD_TOKEN: ${{ secrets.OWNCLOUD_TOKEN }}
      run: |
        RUNNER_WORKSPACE=${RUNNER_WORKSPACE//\\//} >> GITHUB_ENV
        echo VCPKG_DEFAULT_TRIPLET=$VCPKG_DEFAULT_TRIPLET >> $GITHUB_ENV
        echo OWNCLOUD_TOKEN >> $GITHUB_ENV

    - name: Setup environment
      uses: ./.github/actions/setup-environment
    - name: Setup vcpkg binary registry
      run: |
        CWD=$(cd $RUNNER_WORKSPACE; pwd)
        curl -qL -H Authorization: Basic $OWNCLOUD_TOKEN \
          https://freeshell.de/owncloud/remote.php/webdav/CI/vcpkgrc > $CWD/.vcpkgrc
        source $CWD/.vcpkgrc
        echo VCPKG_BINARY_SOURCES=$VCPKG_BINARY_SOURCES >> $GITHUB_ENV
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
          limit-access-to-actor: true
          #install-dependencies: false
      timeout-minutes: 60
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-vcpkgArtifacts
        path: ${{ runner.workspace }}${{ runner.os == 'Windows' && '\' || '/' }}artifacts