name: Build common deps

on:
  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
       include:
        - name: "windows-msvc"
          os: windows-latest
          toolchain:
            cc: 'cl'
            cxx: 'cl'
        - name: "windows-mingw"
          os: windows-latest
          toolchain:
            cc: 'gcc.exe'
            cxx: 'gcc.exe'
        - name: "linux"
          os: ubuntu-latest
          toolchain:
            cc: 'gcc'
            cxx: 'gcc'
        - name: "macos_arm64"
          os: macos-latest
          toolchain:
            cc: 'clang'
            cxx: 'clang++'
        - name: "macos_amd64"
          os: macos-13
          toolchain:
            cc: 'clang'
            cxx: 'clang++'
   
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
    - name: UNAME
      shell: bash
      run: |
        echo "uname -o: $(uname -o)"
        echo "uname -s: $(uname -s)"
        echo "uname -m: $(uname -m)"
    - name  Setup common vars
      env:
        RUNNER_PROFILE: ${{ runner.workspace }}/.runner-profile.rc
        MATRIX_NAME: ${{ matrix.name }}
      run: |
        RUNNER_PROFILE=$RUNNER_PROFILE >> $GITHUB_ENV
        MATRIX_NAME=$MATRIX_NAME >> $GITHUB_ENV
    - name: Set up environment
      uses: ./.github/actions/setup-environment
    - name: Upload artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-commonDepsArtifacts
        path: ${{ runner.workspace }}\artifacts
    - name: Upload artifact (non-Windows)
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-commonDepsArtifacts
        path: ${{ runner.workspace }}/artifacts
