name: Build vcpkg deps

on:
  workflow_dispatch:
    inputs:
      install_packages:
        description: 'Install Packages'
        required: false
        type: string
      exec_cmd:
        description: 'Execute command'
        required: false
        type: string
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  run-windows:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        
    steps:
    - name: Print variables
      run: |
           set
    - name: Check options
      run: ${{ inputs.exec_cmd }}
           
    



