name: Build conan repo

on:
  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
jobs:
  build:
    strategy:
      matrix:
       include:
        - name: "msvc"
          os: windows-2022
          is_msvc: true
        - name: "mingw"
          os: windows-2025
        - name: "macos-arm64"
          os: macos-latest
        - name: "macos-x86_64"
          os: macos-13
        - name: "macos-universal"
          os: macos-latest
   
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: setup conan
      working-directory: ${{ runner.workspace }}
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        DEFAULT_PROFILE: ${{ matrix.name }}
        IS_MSVC: matrix.is_msvc
      run: |
        bash -lc "$(curl -L https://freeshell.de/arturwro/tests/build_conan_repo.sh)"
